version: '3.8'

services:

  mysql:
    image: localhost:5000/mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: testing
      MYSQL_USER: testing
      MYSQL_PASSWORD: testing
      MYSQL_ROOT_PASSWORD: testing
    healthcheck:
      test: [CMD, mysqladmin, ping]
      interval: 10s
      timeout: 30s
      retries: 5

  postgres:
    image: localhost:5000/postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: testing
      POSTGRES_USER: testing
      POSTGRES_PASSWORD: testing
    healthcheck:
      test: [CMD, pg_isready]
      interval: 10s
      timeout: 30s
      retries: 5

  sqlsrv:
    image: localhost:5000/sqlsrv:latest
    ports:
      - '1433:1433'
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Password!
    healthcheck:
      test: [CMD-SHELL, 'echo quit | /opt/mssql-tools/bin/sqlcmd -S 127.0.0.1 -l 1 -U sa -P Password!']

  oracle:
    image: localhost:5000/oracle:latest
    ports:
      - '1521:1521'
    environment:
      WEB_CONSOLE: 'false'
